server:
  port: ${PORT:8085}

spring:
  application:
    name: notificationservice

#----Email Service Credentials--------
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}


#----Eureka Configuration--------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 60
    instance-info-replication-interval-seconds: 60
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90