server:
  port: ${PORT:8085}

spring:
  application:
    name: notificationservice

#----Email Service Credentials--------
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}


#----Eureka Configuration--------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}