server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hrishi-mane/lms-config-server
          search-paths: src/main/resources/config-repo
          default-label: master
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, env, refresh
  endpoint:
    health:
      show-details: always
